
// Define genre options for books used as enum values in database
export const GenreOptions = {
  Action: "Action",
  Dystopian: "Dystopian",
  Fantasy: "Fantasy",
  Historical: "Historical",
  Horror: "Horror",
  Literary: "Literary",
  Mystery: "Mystery",
  Romance: "Romance",
  Science: "Science",
  Thriller: "Thriller",
  Western: "Western",
  Biography: "Biography",
  Autobiography: "Autobiography",
  Memoir: "Memoir",
  FoodDrink: "Food & Drink",
  History: "History",
  SelHelp: "Self-Help",
  Crime: "Crime",
  Travel: "Travel",
  Contemporary: "Contemporary",
  PopCulture: "Pop Culture",
  Nonfiction: "Non-Fiction",
  Fiction: "Fiction",
  War: "War/Militarian",
  Sports: "Sports",
  Comedy: "Comedy",
  Mythology: "Mythology",
  Dark: "Dark",
  Utopian: "Utopian",
  GraphicNovels: "Graphic Novel",
  ShortStory: "Short Story",
  Poetry: "Poetry",
  Religious: "Religious",
  Inspirational: "Inspirational",
  Philosophical: "Philosophical",
  Political: "Political",
  Folklore: "Folklore",
  Social: "Social",
  Conspiracy: "Conspiracy",
  Legal: "Legal",
  Financial: "Financial",
  Supernatural: "Supernatural",
  Academic: "Academic",
  Fashion: "Fashion",
  Business: "Business",
  Arts: "Arts",
  Environmental: "Environmental",
  Entertainment: "Entertainment",
  Global: "Global",
  Medical: "Medical",
  Technical: "Technical",
  LGBTQ: "LGBTQ+",
  Feminist: "Feminist",
  Childrens: "Children's",
  YoungAdult: "Young Adult",
  Apocalyptic: "Apocalyptic",
  Animals: "Animals",
  Ebook: "E-book",
  Erotica: "Erotica",
  Family: "Family",
  Fitness: "Fitness",
  Gaming: "Gaming",
  Goth: "Goth",
  Therapy: "Therapy",
  Teaching: "Teaching",
  Adventure: "Adventure",
  Suspense: "Suspense",
  Genetics: "Genetics",
  AI: "Artificial Intelligence",
  Nautical: "Nautical",
  Technological: "Technological",
  Holiday: "Holiday",
  Health: "Health",
  Cyberpunk: "Cyberpunk",
  Ethnic: "Ethnic",
  Fae: "Fae/Fairy",
  Dragons: "Dragons",
  Steampunk: "Steampunk",
  Vampires: "Vampires",
  Werewolves: "Werewolves",
  Magic: "Magic",
};

const sortedGenres = Object.values(GenreOptions).sort();

export const AllGenres = Object.values(sortedGenres);
